name: 'Deploy ASP.NET Core app to Azure Web App'

on:
  push:
    branches:
      - "main"

inputs:
  AZURE_FUNCTIONAPP_NAME:
    description: 'Azure Name for FunctionApp'
    required: true
  AZURE_FUNCTIONAPP_PACKAGE_PATH:
    description: 'Azure Package Path for FunctionApp'
    required: true
  AZURE_FUNCTIONAPP_PUBLISH_PROFILE:
    description: 'Azure Publish Profile for FunctionApp'
    required: true
  TEAMS_WEBHOOK:
    description: 'ChatOps Webhook for Ms Teams Channel Connector'
    required: true
  DOTNET_VERSION:
    description: 'Version of .Net Core to target'
    required: true

runs:
    using: "composite"
    steps:
      # Checkout the repo
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Setup DotNet Environment
        uses: actions/setup-dotnet@v1
        with:
           dotnet-version: ${{ inputs.DOTNET_VERSION }}

      - name: Restore & Build Function App
        working-directory: '${{ inputs.AZURE_FUNCTIONAPP_DIR_PATH }}'
        shell: bash
        run: |
          pushd '${{ inputs.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd
      - name: Run Azure Functions Action
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ inputs.AZURE_FUNCTIONAPP_NAME }}
          package: '${{ inputs.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          publish-profile: ${{ inputs.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

      # Send Chat Ops notification
      - name: Send chat ops notification to teams
        uses: dhollerbach/actions.send-message-to-ms-teams@1.0.10
        with:
          webhook: ${{ inputs.TEAMS_WEBHOOK }}
          message: 'Deployment Completed for commit: ${{ github.sha }}'
