name: Preprod create envs & secrets

# This will run when kicked off manually or by trigger
on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        description: 'Environment Name'
        required: true
        default: 'preprod'
      PULLED_FROM_KEYVAULT:
        description: 'Pulled from KeyVault'
        required: false
        default: 'PULLED_FROM_KEYVAULT'
      PULLED_FROM_CYBERARK:
        description: 'Pulled from Cyberark'
        required: false
        default: 'PULLED_FROM_CYBERARK'
      PULLED_FROM_SQL:
        description: 'Pulled from sql server'
        required: false
        default: 'PULLED_FROM_SQL'
      PULLED_FROM_BLOB:
        description: 'Pulled from Blob Storage'
        required: false
        default: 'PULLED_FROM_BLOB'
      PULLED_FROM_FILE:
        description: 'Pulled from some file'
        required: false
        default: 'PULLED_FROM_FILE'
      GITHUB_REPO_BRANCH:
        description: 'GitHub Repo Branch'
        required: true
        default: 'main'
      GITHUB_ORG_NAME:
        description: 'GitHub Org Name'
        required: true
        default: 'HomeAidePi-Alpha'
      GITHUB_REPO_NAME:
        description: 'GitHub Repo Name'
        required: true
        default: 'GitHubEnvironments-Actions'
      GITHUB_REPO_TOKEN:
        description: 'Github Repo Token'
        required: true
        default: ''

jobs:
  build:
    name: Build
    timeout-minutes: 3
    strategy:
      matrix:
        os: [ubuntu-latest]
    # todo implement quality strategy after tiger team committee approval
    # package:
    #   - coding-standard
    #   - lint-rules (eslint, flake8)
    #   - commit-guidelines
    #   - pull-request-peer-review
    #   - quality-check
    runs-on: ${{ matrix.os }}
    environment:  ${{ github.event.inputs.ENVIRONMENT }}
    # todo Implement principle of least priv based on need
    permissions:
      contents: 'write'
      id-token: 'write'
      issues: 'write'
      actions: 'write'
      deployments: 'write'
      repository-projects: 'write'
    steps:
    # Checkout the repo
    - uses: actions/checkout@v3
    # Create a GitHub Repo, populate base code
    - uses: ./.github/environments/ci-cq-cd
      with:
          ENVIRONMENT:  ${{ github.event.inputs.ENVIRONMENT }}
          GITHUB_REPO_TOKEN: ${{ github.event.inputs.GITHUB_REPO_TOKEN }}
          GITHUB_REPO_BRANCH: ${{ github.event.inputs.GITHUB_REPO_BRANCH }}
          GITHUB_REPO_NAME: ${{ github.event.inputs.GITHUB_REPO_NAME }}
          GITHUB_ORG_NAME: ${{ github.event.inputs.GITHUB_ORG_NAME }}
          PULLED_FROM_KEYVAULT: ${{ github.event.inputs.PULLED_FROM_KEYVAULT }}
          PULLED_FROM_CYBERARK: ${{ github.event.inputs.PULLED_FROM_CYBERARK }}
          PULLED_FROM_SQL: ${{  github.event.inputs.PULLED_FROM_SQL }}
          PULLED_FROM_BLOB: ${{  github.event.inputs.PULLED_FROM_BLOB }}
          PULLED_FROM_FILE: ${{  github.event.inputs.PULLED_FROM_FILE }}
    
    # PULLED_FROM_QUEUE: ${{ secrets.PULLED_FROM_QUEUE }}
    # PULLED_FROM_STREAM: ${{ secrets.PULLED_FROM_STREAM }}
    # PULLED_FROM_HTTP: ${{ secrets.PULLED_FROM_HTTP }}
    # PULLED_FROM_SERVICE: ${{ secrets.PULLED_FROM_SERVICE }}

  # todo Perform quality checks & standards here
