name: 'Deploy ASP.NET Core app to Azure Web App'

inputs:
  AZURE_FUNCTIONAPP_DIR_PATH:
    description: 'Azure Dir of the FunctionApp source'
    required: true
  AZURE_FUNCTIONAPP_NAME:
    description: 'Azure Name for FunctionApp'
    required: true
  AZURE_FUNCTIONAPP_PACKAGE_PATH:
    description: 'Azure Package Path for FunctionApp'
    required: true
  AZURE_FUNCTIONAPP_PUBLISH_PROFILE:
    description: 'Azure Publish Profile for FunctionApp'
    required: true

runs:
    using: "composite"
    steps:
      # Checkout the repo
      - name: Checkout the repo
        uses: actions/checkout@v3

      # Setup .NET Core SDK & Build
      - name: Setup DotNet Environment
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.x.x
      - run: dotnet build ${{ inputs.AZURE_FUNCTIONAPP_DIR_PATH }}   
        shell: bash
      - run: dotnet test ${{ inputs.AZURE_FUNCTIONAPP_DIR_PATH }}
        shell: bash

      # Restore & Build
      # - name: Restore & Build Function App
      #   working-directory: '${{ inputs.AZURE_FUNCTIONAPP_DIR_PATH }}'
      #   shell: bash
      #   run: |
      #     pushd '${{ inputs.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
      #     dotnet build --configuration Release --output ./output
      #     popd

      # Publish to artifact store
      - name: Publish artifact to store
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.AZURE_FUNCTIONAPP_NAME }}
          path: '${{ inputs.AZURE_FUNCTIONAPP_DIR_PATH }}/${{ inputs.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
  
      # Promote images in artifact store
      - name: Download artifact from store
        uses: actions/download-artifact@v3
        with:
          name:  ${{ inputs.AZURE_FUNCTIONAPP_NAME }}

      # Run Azure Action 
      - name: Run Azure Functions Action
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ inputs.AZURE_FUNCTIONAPP_NAME }}
          package: '.'
          publish-profile: ${{ inputs.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
