name: 'Provision Azure App Service with Terraform'

inputs:
  ENVIRONMENT:
    description: Enviroment Name
    required: true
  AZURE_APP_SERVICE_NAME:
    description: 'Name of the Function App Service'
    required: true
  AZURE_AD_CLIENT_ID:
    description: 'Azure Client Id'
    required: true
  AZURE_AD_TENANT_ID:
    description: 'Azure Tenant Id'
    required: true
  AZURE_SUBSCRIPTION_ID:
    description: 'Azure Subscription Id'
    required: true
  AZURE_RESOURCE_GROUP:
    description: 'Azure Resource Group'
    required: true
  AZURE_RESOURCE_GROUP_NAME:
    description: 'Azure Resource Group Name'
    required: true
  AZURE_STORAGE_ACCOUNT_NAME: 
    description: 'Azure Storage Account Name'
    required: true
  AZURE_STORAGE_CONTAINER_NAME:
    description: 'Azure Storage Container Name'
    required: true
  AZURE_REGION:
    description: 'Azure Region'
    required: true

runs:
    using: "composite"
    steps:
      # Checkout the repo
      - name: Checkout the repo
        uses: actions/checkout@v3

      # Terraform Azure resources
      - name: Terraform Azure Resources
        uses: ./.github/workflows/ci-cd/terraform/azure
        with:
          ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
          TERRAFORM_WORKING_DIR: './.github/workflows/ci-cd/terraform/azure'
          AZURE_APP_SERVICE_NAME: ${{ inputs.AZURE_APP_SERVICE_NAME }}
          AZURE_AD_CLIENT_ID: ${{ inputs.AZURE_AD_CLIENT_ID }}
          AZURE_AD_TENANT_ID: ${{ inputs.AZURE_AD_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ inputs.AZURE_SUBSCRIPTION_ID }}
      