name: "TODO Code into Issue"
on: ["push"]
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: Check out Repo
        uses: actions/checkout@v3

      - name: "TODO into Issue"
        uses: "alstr/todo-to-issue-action@master"
        with:
          REPO: ${{ github.repository }}
          BEFORE: ${{ github.event.before }}
          SHA: ${{ github.sha }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABEL: "# TODO"
          COMMENT_MARKER: "#"
        id: "todo"