name: 'Terraform Azure '
 
inputs:
  ENVIRONMENT:
    description: 'Environment Name'
    required: true
  AZURE_AD_CLIENT_ID:
    description: 'Azure Client Id'
    required: true
  AZURE_AD_TENANT_ID:
    description: 'Azure Tenant Id'
    required: true
  AZURE_SUBSCRIPTION_ID:
    description: 'Azure Subscription Id'
    required: true
  AZURE_LOCATION:
    description: 'Azure Region/Location'
    required: true
  AZURE_FUNCTION_APP_NAME:
    description: 'Name of the Function App'
    required: true
  AZURE_RESOURCE_GROUP_NAME:
    description: 'Azure Resource Group Name'
    required: true
  AZURE_SERVICE_PLAN_ID:
    description: 'Azure Service Plan Id'
    required: true
  AZURE_STORAGE_ACCOUNT_NAME:
    description: 'Azure Storage Account Name'
    required: true
  AZURE_STORAGE_ACCOUNT_ACCESS_KEY:
    description: 'Azure Storage Account Access Key'
    required: true

runs:
    using: "composite"
    defaults:
      run:
        working-directory: ./.github/workflows/ci-cd/terraform/azure/functionApp
    steps:
      # Checkout the repo
      - name: Checkout the repo
        uses: actions/checkout@v3
 
      # Terraform Format 
      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.14.8
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: './functionApp'

      # Terraform Init
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.14.8
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: .
        env:
            TF_CLI_ARGS_init: '-var="env=${{inputs.ENVIRONMENT}}"
                               -var="client-id=${{inputs.AZURE_AD_CLIENT_ID}}" 
                               -var="tenant-id=${{inputs.AZURE_AD_TENANT_ID}}"
                               -var="subscription-id=${{inputs.AZURE_SUBSCRIPTION_ID}}"
                               -var="function-app-name=${{inputs.AZURE_FUNCTION_APP_NAME}}"
                               -var="resource-group-name=${{inputs.AZURE_RESOURCE_GROUP_NAME}}"
                               -var="location=${{inputs.AZURE_LOCATION}}"
                               -var="service-plan-id=${{inputs.AZURE_SERVICE_PLAN_ID}}"
                               -var="storage-account-name=${{inputs.AZURE_STORAGE_ACCOUNT_NAME}}"
                               -var="storage-account-access-key=${{inputs.AZURE_STORAGE_ACCOUNT_ACCESS_KEY}}"
                              '

      # Terraform Validate
      - name: 'Terraform Validate'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.14.8
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: './functionApp'
         
      # Terraform Plan
      - name: 'Terraform Plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.14.8
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: './functionApp'

      # Terraform Apply
      - name: Terraform Apply
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.14.8
          tf_actions_subcommand: 'apply'
          tf_actions_working_dir: './functionApp'