name: 'Terraform Azure '
 
inputs:
  ENVIRONMENT:
    description: 'Environment Name'
    required: true
  AZURE_APP_SERVICE_NAME:
    description: 'Name of the Function App Service'
    required: true
  TERRAFORM_WORKING_DIR:
    description: 'Terraform Working File Path'
    required: true
  AZURE_AD_CLIENT_ID:
    description: 'Azure Client Id'
    required: true
  AZURE_AD_TENANT_ID:
    description: 'Azure Tenant Id'
    required: true
  AZURE_SUBSCRIPTION_ID:
    description: 'Azure Subscription Id'
    required: true

runs:
    using: "composite"
    steps:
      # Checkout the repo
      - name: Checkout the repo
        uses: actions/checkout@v3
 
      # Terraform Format 
      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.14.8
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: ${{inputs.TERRAFORM_WORKING_DIR}}

      # Terraform Init
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.14.8
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: ${{inputs.TERRAFORM_WORKING_DIR}}
        env:
            TF_CLI_ARGS_init: '-var="env=${{inputs.ENVIRONMENT}}" 
                               -var="app-service-name=${{inputs.AZURE_APP_SERVICE_NAME}}" 
                               -var="client-id=${{inputs.AZURE_AD_CLIENT_ID}}" 
                               -var="tenant-id=${{inputs.AZURE_AD_TENANT_ID}}"
                               -var="subscription-id=${{inputs.AZURE_SUBSCRIPTION_ID}}"
                              '

      # Terraform Validate
      - name: 'Terraform Validate'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.14.8
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: ${{inputs.TERRAFORM_WORKING_DIR}}
         
      # Terraform Plan
      - name: 'Terraform Plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.14.8
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: ${{inputs.TERRAFORM_WORKING_DIR}}

      # Terraform Apply
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.14.8
          tf_actions_subcommand: 'apply'
          tf_actions_working_dir: ${{inputs.TERRAFORM_WORKING_DIR}}