name: Create a GitHub Repo, populate base code & create environments

inputs:
  USER_NAME:
    description: 'User Name'
    required: true
  USER_EMAIL:
    description: 'User Email'
    required: true
  GITHUB_ORG_NAME:
    description: 'GitHub Organization Name'
    required: true
  GITHUB_REPO_BRANCH:
    description: 'GitHub Repo Branch Name usually "main" or  "master"'
    required: true
  GITHUB_REPO_NAME:
    description: 'GitHub Repo Name'
    required: true
  GITHUB_REPO_TOKEN:
    description: 'GitHub Repo Token for Auth'
    required: true

runs:
    using: "composite"
    steps:
      # Checkout the repo
    - name: Check out Repo
      uses: actions/checkout@v3
      
    # Push the workflows to the repo
    - name: Push workflows to the repo
      shell: bash
      run: |
        git config --global user.name ${{ inputs.USER_NAME }}
        git config --global user.email ${{ inputs.USER_EMAIL }}
        git remote set-url --add --push origin "https://${{ inputs.GITHUB_REPO_TOKEN}}@github.com/${{ inputs.GITHUB_ORG_NAME}}/${{ inputs.GITHUB_REPO_NAME}}.git"
        git status
        git add workflows/phase1-alpha-python-executed.yaml
        git mv workflows/phase1-alpha-python-executed.yaml .github/workflows/phase1-alpha-python-executed.yaml
        git add workflows/quality-codeql.yaml
        git mv workflows/quality-codeql.yaml .github/workflows/quality-codeql.yaml
        git add workloads
        git mv workloads .github/workflows
        git commit -m "Add workflows after envs are setup"
        git push -f origin ${{ inputs.GITHUB_REPO_BRANCH }}
