name: 'Deploy ASP.NET Core app to Azure Web App'

on:
  push:
    branches:
      - "main"

inputs:
  AZURE_CLIENT_ID:
    description: 'Azure Client Id'
    required: true
  AZURE_TENANT_ID:
    description: 'Azure Tenant Id'
    required: true
  AZURE_SUBSCRIPTION_ID:
    description: 'Azure Subscription Id'
    required: true
  TEAMS_WEBHOOK:
    description: 'ChatOps Webhook for Ms Teams Channel Connector'
    required: true
  AZURE_CLI_VERSION:
    description: 'Version of Azure Cli to Target'
    required: true

runs:
    using: "composite"
    steps:
      # Checkout the repo
      - name: Checkout the repo
        uses: actions/checkout@v3
        
      - name: 'Az CLI Login via OIDC'
        uses: azure/login@v1
        with:
          client-id: ${{ inputs.AZURE_CLIENT_ID }}
          tenant-id: ${{ inputs.AZURE_TENANT_ID }}
          subscription-id: ${{ inputs.AZURE_SUBSCRIPTION_ID }}

      - name: "Add a mask to the SWA Token"
        uses: azure/CLI@v1
        with:
          azcliversion: ${{ env.AZURE_CLI_VERSION }}
          inlineScript: |
                        echo "::add-mask::$(az login')"

      # Send Chat Ops notification
      - name: Send chat ops notification to teams
        uses: dhollerbach/actions.send-message-to-ms-teams@1.0.10
        with:
          webhook: ${{ inputs.TEAMS_WEBHOOK }}
          message: 'Deployment Completed for commit: ${{ github.sha }}'
