name: Azure Powershell Composite - OIDC
on:
  workflow_dispatch:

permissions:
  contents: 'read'
  id-token: 'write'

  
jobs:
  job:
    runs-on: ubuntu-latest
    environment: 'PreProd'
    steps:
    - uses: actions/checkout@v3
    #
    #   This section runs the Azure powershell action composite with OIDC
    #
    - uses: ./.github/workflows/azure/powershell/oidc
      with:
        AZURE_AD_CLIENT_ID:  ${{ secrets.AZURE_AD_CLIENT_ID }}
        AZURE_AD_TENANT_ID:  ${{ secrets.AZURE_AD_TENANT_ID }}
        AZURE_SUBSCRIPTION_ID:  ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        TEAMS_WEBHOOK:  ${{ secrets.TEAMS_WEBHOOK }}
 