name: Microsoft Azure CLI - OIDC
on:
  workflow_dispatch:
    inputs: 
      ENVIRONMENT: 
        description: 'Environment Name'
        required: true
        default: preprod

permissions:
  contents: 'read'
  id-token: 'write'
  
jobs:
  login-oidc:
    runs-on: windows-latest
    environment: preprod
    steps:
    # Checkout the Repo
    - uses: actions/checkout@v3
    
    # This section runs the Azure Cli action composite with OIDC
    - uses: ./.github/workflows/clouds/azure/cli/oidc
      with:
        AZURE_AD_CLIENT_ID:  ${{ secrets.AZURE_AD_CLIENT_ID }}
        AZURE_AD_TENANT_ID:  ${{ secrets.AZURE_AD_TENANT_ID }}
        AZURE_SUBSCRIPTION_ID:  ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
  chatops:
    name: Send notifications with Teams
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    steps:
          # Send Chat Ops notification
      - name: Send chat ops notification to teams
        uses: dhollerbach/actions.send-message-to-ms-teams@1.0.10
        with:
          webhook: ${{ inputs.TEAMS_WEBHOOK }}
          message: 'Deployment Completed for commit: ${{ github.sha }} check logs to determine success.'
 