name: Microsoft Azure CI-CQ-CD
on:
  push:
    branches:
      - "main"

permissions:
  contents: 'read'
  id-token: 'write'
  
jobs:
  job:
    runs-on: ubuntu-latest
    environment: 'PreProd'
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/workflows/google
      with:
          GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}