name: Microsoft Azure CI-CQ-CD
on:
  push:
    branches:
      - "main"

permissions:
  contents: 'read'
  id-token: 'write'
  
jobs:
  job:
    runs-on: ubuntu-latest
    environment: 'PreProd'
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/workflows/netCore
      with:
        AZURE_CREDENTIALS:  ${{ secrets.AZURE_CREDENTIALS }}
        AZURE_WEBAPP_PUBLISH_PROFILE:  ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        TEAMS_WEBHOOK:  ${{ secrets.TEAMS_WEBHOOK }}
        DOTNET_VERSION: ${{ env.DOTNET_VERSION }}


