name: Microsoft Azure CI-CQ-CD
on:
  push:
    branches:
      - "main"

permissions:
  contents: 'read'
  id-token: 'write'

env:
  AZURE_CLI_VERSION: '3.1.404'
  
jobs:
  job:
    runs-on: ubuntu-latest
    environment: 'PreProd'
    steps:
    - uses: actions/checkout@v3
    #
    #   This section runs the Azure Cli action composite with OIDC
    #
    - uses: ./.github/workflows/azure
      with:
        AZURE_CLIENT_ID:  ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_TENANT_ID:  ${{ secrets.AZURE_TENANT_ID }}
        AZURE_SUBSCRIPTION_ID:  ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        TEAMS_WEBHOOK:  ${{ secrets.TEAMS_WEBHOOK }}
        AZURE_CLI_VERSION: ${{ env.AZURE_CLI_VERSION }}
 