name: Microsoft Azure CI-CQ-CD
on:
  push:
    branches:
      - "main"

permissions:
  contents: 'read'
  id-token: 'write'

env:
  DOTNET_VERSION: '3.1.404'
  
jobs:
  job:
    runs-on: ubuntu-latest
    environment: 'PreProd'
    steps:
    - uses: actions/checkout@v3
    #
    #   This section runs the Azure NetCore Build and Publish action workflow with Creds
    #
    - uses: ./.github/workflows/azure/netCore
      with:
        AZURE_CREDENTIALS:  ${{ secrets.AZURE_CREDENTIALS }}
        AZURE_WEBAPP_PUBLISH_PROFILE:  ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
        AZURE_WEBAPP_DIR_PATH: ${{ secrets.AZURE_WEBAPP_DIR_PATH }}
        AZURE_WEBAPP_PACKAGE_PATH: ${{ secrets.AZURE_WEBAPP_PACKAGE_PATH }}
        #AZURE_WEBAPP_SLOT_NAME: ${{ secrets.AZURE_WEBAPP_SLOT_NAME }}
        TEAMS_WEBHOOK:  ${{ secrets.TEAMS_WEBHOOK }}
        DOTNET_VERSION: ${{ env.DOTNET_VERSION }}


