name: Azure Spring Cloud Java Spring Boot

on:
  workflow_dispatch:
    inputs: 
      ENVIRONMENT:
        description: 'Environment'
        required: true
        default: 'preprod'
      AZURE_APP_NAME:
        description: 'Name of the Spring Cloud App'
        required: true
        default: 'alpha-sc-app'
      AZURE_SERVICE_INSTANCE_NAME:
        description: 'Name of the Service Instance'
        required: true
        default: 'alpha-sc-service'
      AZURE_RESOURCE_GROUP_NAME:
        description: 'Azure Resource Group Name'
        required: true
        default: 'HomeAidePi'
      AZURE_LOCATION:
        description: 'Azure Region/Location'
        required: true
        default: 'centralus'

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  # provision:
  #   name: Provision Azure Spring Boot App
  #   runs-on: ubuntu-latest
  #   environment: ${{ github.event.inputs.ENVIRONMENT }}

  #   steps:  
  #   # Checkout the Repo
  #   - uses: actions/checkout@v3

  #   # Provision using composite
  #   - name: Provision Azure Spring Boot App with Azure Cli
  #     uses: ./.github/workflows/clouds/azure/springCloud/springBoot/oidc/provision
  #     with:
  #       AZURE_AD_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
  #       AZURE_AD_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
  #       AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  #       AZURE_LOCATION: ${{ github.event.inputs.AZURE_LOCATION }}
  #       AZURE_SERVICE_INSTANCE_NAME: ${{ github.event.inputs.AZURE_SERVICE_INSTANCE_NAME }}
  #       AZURE_RESOURCE_GROUP_NAME: ${{ github.event.inputs.AZURE_RESOURCE_GROUP_NAME }}
  #       AZURE_APP_NAME:  ${{ github.event.inputs.AZURE_APP_NAME }}

  deploy:
    name: Deploy from source code build
    # needs: [provision]
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.ENVIRONMENT }}
    steps:
      # Check out the repo
      - name: Checkout Github Action
        uses: actions/checkout@v2

      # Setup Java runtime & Build with gradle
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Change wrapper permissions to allow it to execute a build
        run: chmod +x ./workloads/java/springBoot/petClinic/gradlew
      
      - name: Build with Gradle
        run: ./workloads/java/springBoot/petClinic/gradlew build --no-daemon
          
      # Login to Azure with CLI with Federated with Github
      - name: Az CLI Login via OIDC
        uses: azure/login@v1.4.0
        with:
          client-id: ${{ secrets.AZURE_AD_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_AD_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Deploy the Spring Cloud app 
      - name: deploy step from source code built in the earlier provision composite
        uses: azure/spring-cloud-deploy@v1
        with:
          azure-subscription: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          action: deploy
          service-name: ${{ github.event.inputs.AZURE_SERVICE_INSTANCE_NAME }}
          app-name: ${{ github.event.inputs.AZURE_APP_NAME }}
          use-staging-deployment: false
          package:  ./workloads/java/springBoot/petClinic/**/*.jar