name: Google Cloud Login with Identity Provider
on:
  push:
    branches:
      - "main"

permissions:
      id-token: write
      contents: read

jobs:
  gcp_job_id_alpha:
    name: "Login GCP with Identity Provider"
    runs-on: windows-latest
    environment: 'PreProd'
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider:  ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'
      