name: Google Cloud CLI Composite - Service Account
on:
  workflow_dispatch:

permissions:
  contents: 'read'
  id-token: 'write'
  
jobs:
  job:
    runs-on: ubuntu-latest
    environment: 'PreProd'
    steps:
    - uses: actions/checkout@v3
    #
    #   This section runs the Google cli action composite with Service Account
    #
    - uses: ./.github/workflows/gcp/cli/service-account
      with:
          GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}