name: Create a GitHub Repo and populate code

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'GitHub Repo Branch'
        required: true
        default: 'origin/main'
      org_name:
        description: 'GitHub Org Name'
        required: true
        default: 'homeaidepi'
      repo_name:
        description: 'GitHub Repo Name'
        required: true
        default: 'GitHubEnvironments-Alpha'
      user_name:
        description: 'GitHub User Name'
        required: true
        default: 'matthew.vandergrift@homeaidepi.com'
      user_email:
        description: 'GitHub User Email'
        required: true
        default: 'matthew.vandergrift@homeaidepi.com'
      files:
        description: 'GitHub Repo Files'
        required: true
        default: './.github/workflows/github/repo/python/files'
      file_list:
        description: 'GitHub Repo File List'
        required: true
        default: './.github/workflows/github/repo/python/alpha.py'
      token:
        description: 'GitHub Token'
        required: true
        default: ''
      webhook:
        description: 'Teams Webhook'
        required: false
        default: ''
      url:
        description: 'GitHub Repo URL'
        required: true
        default: 'https://github.com/HomeAidePi-Alpha/GitHubEnvironments-Alpha.git'

jobs:
  job:
    runs-on: self-hosted
    environment: 'PreProd'
    permissions:
      contents: 'write'
      id-token: 'write'
      issues: 'write'
      actions: 'write'
      deployments: 'write'
      repository-projects: 'write'

    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/workflows/github/repo
      with:
          TEAMS_WEBHOOK: ${{ github.event.inputs.webhook }}
          GITHUB_REPO_TOKEN: ${{ github.event.inputs.token }}
          GITHUB_REPO_BRANCH: ${{ github.event.inputs.branch }}
          GITHUB_REPO_NAME: ${{ github.event.inputs.repo_name }}
          GITHUB_USER_EMAIL: ${{ github.event.inputs.user_email }}
          GITHUB_USER_NAME: ${{ github.event.inputs.user_name }}
          GITHUB_ORG_NAME: ${{ github.event.inputs.org_name }}
          GITHUB_REPO_FILES: ${{ github.event.inputs.files }}
          GITHUB_REPO_URL: ${{ github.event.inputs.url }}
          GITHUB_REPO_FILE_LIST: ${{ github.event.inputs.file_list }}
