name: Preprod create a GitHub Repo and populate code, create secrets, docs & wiki, test for quality and check standards

# This will run when kicked off manually or by trigger
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'GitHub Repo Branch'
        required: true
        default: 'main'
      org_name:
        description: 'GitHub Org Name'
        required: true
        default: 'HomeAidePi-Alpha'
      repo_name:
        description: 'GitHub Repo Name'
        required: true
        default: 'GitHubEnvironments-Alpha'
      user_name:
        description: 'GitHub User Name'
        required: true
        default: 'Vandy'
      user_email:
        description: 'GitHub User Email'
        required: true
        default: 'matthew.vandergrift@homeaidepi.com'
      files:
        description: 'GitHub Repo Files'
        required: true
        default: './.github/workflows/github/repo/python'
      file_list:
        description: 'GitHub Repo File List'
        required: true
        default: './.github/workflows/github/repo/python/alpha.py'
      token:
        description: 'GitHub Token'
        required: true
        default: ''
      teams_webhook:
        description: 'Teams Webhook'
        required: false
        default: ''
      slack_user_name: 
        description: 'Slack Username'
        required: false
        default: ''
      slack_webhook:
        description: 'Slack Webhook'
        required: false
        default: ''
      url:
        description: 'GitHub Repo URL'
        required: true
        default: 'https://github.com/HomeAidePi-Alpha/GitHubEnvironments-Alpha.git'

jobs:
  build:
    name: Phase-1-Alpha
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest]
        # todo implement quality strategy after tiger team committee approval
        # package:
        #   - coding-standard
        #   - lint-rules (eslint, flake8)
        #   - commit-guidelines
        #   - pull-request-peer-review
        #   - quality-checks

    runs-on: ${{ matrix.os }}
   
    environment: preprod
    
    # todo Implement principle of least priv based on need
    permissions:
      contents: 'write'
      id-token: 'write'
      issues: 'write'
      actions: 'write'
      deployments: 'write'
      repository-projects: 'write'

    steps:
    - uses: actions/checkout@v3
    # Create a GitHub Repo, populate base code
    - uses: ./.github/workflows/github/repo
      with:
          GITHUB_REPO_TOKEN: ${{ github.event.inputs.token }}
          GITHUB_REPO_BRANCH: ${{ github.event.inputs.branch }}
          GITHUB_REPO_NAME: ${{ github.event.inputs.repo_name }}
          GITHUB_USER_EMAIL: ${{ github.event.inputs.user_email }}
          GITHUB_USER_NAME: ${{ github.event.inputs.user_name }}
          GITHUB_ORG_NAME: ${{ github.event.inputs.org_name }}
          GITHUB_REPO_FILES: ${{ github.event.inputs.files }}
          GITHUB_REPO_URL: ${{ github.event.inputs.url }}
          GITHUB_REPO_FILE_LIST: ${{ github.event.inputs.file_list }}

    # Allow former API operations to complete with an artifical 10 second wait
    - name: Wait for 10 seconds
      shell: bash
      run: sleep 10s

    # Create secrets, docs & wiki, test for quality and check standards
    - uses: ./.github/workflows/github/repo/environments/preprod
      with:
          ENVIRONMENT: preprod
          GITHUB_REPO_TOKEN: ${{ github.event.inputs.token }}
          GITHUB_REPO_BRANCH: ${{ github.event.inputs.branch }}
          GITHUB_REPO_NAME: ${{ github.event.inputs.repo_name }}
          GITHUB_ORG_NAME: ${{ github.event.inputs.org_name }}

    # Send a chat ops notification depending on teams or slack
    - uses: ./.github/workflows/chatops/teams
      with:
          ENVIRONMENT: preprod
          TEAMS_WEBHOOK: ${{ github.event.inputs.teams_webhook }}

    # Send a chat ops notification depending on slack
    - uses: ./.github/workflows/chatops/slack
      with:
          ENVIRONMENT: preprod
          SLACK_USER_NAME: ${{ github.event.inputs.slack_user_name }}
          SLACK_WEBHOOK: ${{ github.event.inputs.slack_webhook }}

    # todo Perform quality checks & standards here
