name: Production create a GitHub Repo and populate code, create secrets, docs & wiki, test for quality and check standards
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'GitHub Repo Branch'
        required: true
        default: 'main'
      org_name:
        description: 'GitHub Org Name'
        required: true
        default: 'HomeAidePi-Alpha'
      repo_name:
        description: 'GitHub Repo Name'
        required: true
        default: 'GitHubEnvironments-Alpha'
      user_name:
        description: 'GitHub User Name'
        required: true
        default: 'Vandy'
      user_email:
        description: 'GitHub User Email'
        required: true
        default: 'matthew.vandergrift@homeaidepi.com'
      files:
        description: 'GitHub Repo Files'
        required: true
        default: './.github/workflows/github/repo/python'
      file_list:
        description: 'GitHub Repo File List'
        required: true
        default: './.github/workflows/github/repo/python/alpha.py'
      token:
        description: 'GitHub Token'
        required: true
        default: ''
      webhook:
        description: 'Teams Webhook'
        required: false
        default: ''
      url:
        description: 'GitHub Repo URL'
        required: true
        default: 'https://github.com/HomeAidePi-Alpha/GitHubEnvironments-Alpha.git'

jobs:
  #Phase 1 - Alpha
  job:
    runs-on: ubuntu-latest
    # todo implement quality strategy by tiger team committee
    # strategy:
    #   matrix:
    #       package:
    #           - coding-standard
    #           - python-lint-rules
    #           - commit-guidelines
    #           - pull-request-peer-review
    #           - quality-checks
    environment: prod
    # todo Implement principle of least priv based on need
    permissions:
      contents: 'write'
      id-token: 'write'
      issues: 'write'
      actions: 'write'
      deployments: 'write'
      repository-projects: 'write'

    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/workflows/github/repo/environments/prod
      with:
          ENVIRONMENT: prod
          GITHUB_REPO_TOKEN: ${{ github.event.inputs.token }}
          GITHUB_REPO_BRANCH: ${{ github.event.inputs.branch }}
          GITHUB_REPO_NAME: ${{ github.event.inputs.repo_name }}
          GITHUB_ORG_NAME: ${{ github.event.inputs.org_name }}
