name: Create a GitHub Repo and populate code
  
on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'GitHub Repo Branch'     
        required: true
        default: 'origin/main'
      name:
        description: 'GitHub Repo Name'     
        required: true
        default: 'GitHubEnvironments-Alpha'
      email:
        description: 'GitHub Repo Email'     
        required: true
        default: 'matthew.vandergrift@homeaidepi.com'
      files:
        description: 'GitHub Repo Files'     
        required: true
        default: './github/workflows/github/repo/files'
      file_list:
        description: 'GitHub Repo File List'     
        required: true
        default: './github/workflows/github/repo/files/alpha.txt ./github/workflows/github/repo/files/beta.txt'
      token:
        description: 'GitHub Token'     
        required: true
        default: ''
      webhook:
        description: 'Teams Webhook'     
        required: true
        default: ''
      url:
        description: 'GitHub Repo URL'     
        required: true
        default: 'https://github.com/HomeAidePi-Alpha/GitHubEnvironments-Alpha.git'
  
jobs:
  job:
    runs-on: ubuntu-latest
    environment: 'PreProd'
    permissions:
      contents: 'write'
      id-token: 'write'
      issues: 'write'
      actions: 'write'
      deployments: 'write'
      repository-projects: 'write'

    steps:
    - uses: ./.github/workflows/github/repo
      with:
          TEAMS_WEBHOOK:  ${{ secrets.TEAMS_WEBHOOK }}
          GITHUB_REPO_TOKEN:  ${{ github.event.inputs.token }}
          GITHUB_REPO_BRANCH:  ${{ github.event.inputs.branch }}
          GITHUB_REPO_EMAIL:   ${{ github.event.inputs.email }}
          GITHUB_REPO_NAME:   ${{ github.event.inputs.name }}
          GITHUB_REPO_FILES:  ${{ github.event.inputs.files }}
          GITHUB_REPO_URL:  ${{ github.event.inputs.url }}
          GITHUB_REPO_FILE_LIST:  ${{ github.event.inputs.file_list }}
