name: Production create secrets test for quality and check standards
on:
  workflow_dispatch:
    inputs:
      user_name:
        description: 'User Name'
        required: true
        default: 'Vandy'
      user_email:
        description: 'User Email'
        required: true
        default: 'matthew.vandergrift@homeaidepi.com'
      branch:
        description: 'GitHub Repo Branch'
        required: true
        default: 'main'
      org_name:
        description: 'GitHub Org Name'
        required: true
        default: 'HomeAidePi-Alpha'
      repo_name:
        description: 'GitHub Repo Name'
        required: true
        default: 'GitHubEnvironments-Alpha'
      file_list:
        description: 'GitHub Repo File List'
        required: true
        default: './.github/workflows/github/repo/src/alpha.py'
      token:
        description: 'A Token'
        required: true
        default: ''
      teams_webhook:
        description: 'Teams Webhook'
        required: false
        default: ''
      slack_webhook:
        description: 'Slack Webhook'
        required: false
        default: ''

jobs:
  #Phase 1 - Alpha
  job:
    runs-on: ubuntu-latest
    # todo implement quality strategy by tiger team committee
    # strategy:
    #   matrix:
    #       package:
    #           - coding-standard
    #           - python-lint-rules
    #           - commit-guidelines
    #           - pull-request-peer-review
    #           - quality-checks
    environment: prod
    # todo Implement principle of least priv based on need
    permissions:
      contents: 'write'
      id-token: 'write'
      issues: 'write'
      actions: 'write'
      deployments: 'write'
      repository-projects: 'write'

    steps:
    - uses: actions/checkout@v3
    # perform canary deployment using feature flags on
    - uses: ./.github/workflows/github/repo/environments/prod
      with:
          ENVIRONMENT: prod
          GITHUB_REPO_TOKEN: ${{ github.event.inputs.token }}
          GITHUB_REPO_BRANCH: ${{ github.event.inputs.branch }}
          GITHUB_REPO_NAME: ${{ github.event.inputs.repo_name }}
          GITHUB_ORG_NAME: ${{ github.event.inputs.org_name }}
          
     # Send a chat ops notification on teams or use slack below
    - uses: ./.github/workflows/chatops/teams
      with:
          ENVIRONMENT: preprod
          TEAMS_WEBHOOK: ${{ github.event.inputs.teams_webhook }}

    # Send a chat ops notification on slack
    - uses: ./.github/workflows/chatops/slack
      with:
          ENVIRONMENT: preprod
          USER_NAME: ${{ github.event.inputs.user_name }}
          SLACK_WEBHOOK: ${{ github.event.inputs.slack_webhook }}
    
    # perform your quality checks here

    # if the canary dies rollback the environment or
    # if the canary flies keep the environment and turn feature flag off or
    # if the canary flies keep the environment and leave feature flag on
