name: Google Cloud CI-CQ-CD
on:
  push:
    branches:
      - "main"
jobs:
  job:
    runs-on: ubuntu-latest
    environment: 'PreProd'
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/workflows/google